[package]
name = "aioracle_v2"
version = "0.1.0"
authors = ["Oraichain"]
edition = "2018"
description = "An ai oracle contract using optimistic rollup"
license = "Apache-2.0"

exclude = [
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { version = "0.13.2" }
cw-storage-plus = {  version = "0.5.0" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }
hex = "0.4"
sha2 = { version = "0.9.5", default-features = false }
aioracle_base = {path = '../../base/aioracle_base'}

[dev-dependencies]
cosmwasm-schema = "0.13.2"


