[package]
name = "drand"
version = "0.1.0"
license = "AGPL-3.0"
authors = ["Thanh tu <tu@orai.io>"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "artifacts/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
default = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces", "cosmwasm-vm/backtraces"]
cranelift = ["cosmwasm-vm/cranelift"]

[dependencies]
drand-verify = { path = "../../base/drand-verify" }
cosmwasm-std = { version = "0.13.2", features = ["iterator"] }
cosmwasm-storage = { version = "0.13.2", features = ["iterator"] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0"
[dev-dependencies]
cosmwasm-vm = { version = "0.13.2", default-features = false, features = [
  "iterator",
] }
cosmwasm-schema = { version = "0.13.2" }
