[package]
authors = ["Mauro Lacy <maurolacy@users.noreply.github.com>"]
description = "Implementation of Atomic Swaps"
edition = "2018"
license = "Apache-2.0"
name = "cw20-atomic-swap"
version = "0.6.1"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = {version = "0.14.0", features = ["iterator"]}
cw-storage-plus = {version = "0.6.1", features = ["iterator"]}
cw0 = {version = "0.6.1"}
cw2 = {version = "0.6.1"}
cw20 = {version = "0.6.1"}
hex = "0.3.1"
schemars = "0.8.1"
serde = {version = "1.0.103", default-features = false, features = ["derive"]}
sha2 = "0.8.0"
thiserror = {version = "1.0.20"}

[dev-dependencies]
cosmwasm-schema = {version = "0.14.0"}
