[package]
name = "blsttc"
version = "3.4.0"
authors = [
    "Vladimir Komendantskiy <komendantsky@gmail.com>",
    "Andreas Fackler <AndreasFackler@gmx.de>",
    "Peter van Nostrand <jnz@riseup.net>",
    "Andrew Gross <andogro@gmail.com>",
    "Nick Sanders <nsan1129@gmail.com>",
    "Marc Brinkmann <git@marcbrinkmann.de>",
]
categories = ["cryptography"]
keywords = ["pairing", "threshold"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/maidsafe/blsttc"
description = "Pairing threshold cryptography"
edition = "2018"

[build]
rustflags = ["-I/usr/include"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[dependencies]
byteorder = "1.3.4"
ff = "0.6.0"
group = "0.6.0"
hex_fmt = "0.3.0"
log = "0.4.8"
pairing = "0.16.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
thiserror = "1.0.22"
zeroize = "1.1.0"
cosmwasm-std = { version = "0.13.2" }
cw-storage-plus = { version = "0.5.0", features = ["iterator"] }
cosmwasm-storage = { version = "0.13.2", features = ["iterator"] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
blst = { version = "0.3.3", features = ["portable"] }
tiny-keccak = { version = "2.0.1", features = ["sha3"] }
bincode = { version = "1.2.1", optional = true }
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = [
    "derive",
], optional = true }

[dev-dependencies]
bincode = "1.2.1"
criterion = "0.3.1"
hex = "0.4.3"
rand_xorshift = "0.2.0"
cosmwasm-schema = { version = "0.13.2" }

[[bench]]
name = "bench"
harness = false

[features]
codec-support = ["codec", "bincode"]
