[package]
name = "aioracle_exectors_service"
version = "0.1.0"
authors = ["Oraichain"]
edition = "2018"
license = "Apache-2.0"

exclude = [
  "contract.wasm",
  "hash.txt"
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type=["cdylib","rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { version = "0.13.2" }
cw-storage-plus = {  version = "0.5.0" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }
aioracle_new = {path = "../../base/aioracle_new"}
hex = "0.4"
sha2 = { version = "0.9.5", default-features = false }
bech32 = "0.8.1"
ripemd = "0.1.1"

[dev-dependencies]
cosmwasm-schema = "0.13.2"
aioracle_v2 = {path='../aioracle_v2'}