[package]
name = "cosmwasm_nft"
version = "0.1.0"
authors = ["shiki.tak <shiki.tak@gmail.com>"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "artifacts/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = 'abort'
rpath = false

[features]
default = ["cranelift"]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw0 = { git = "https://github.com/CosmWasm/cosmwasm-plus.git", version = "0.5.0" }
cw2 = { git = "https://github.com/CosmWasm/cosmwasm-plus.git", version = "0.5.0" }
cw721 = { git = "https://github.com/CosmWasm/cosmwasm-plus.git", version = "0.5.0" }
cw-storage-plus = { git = "https://github.com/CosmWasm/cosmwasm-plus.git", version = "0.5.0" , features = ["iterator"]}
cosmwasm-std = {version = "0.13.0"}
schemars = "0.8"
serde = {version = "1.0.103", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.21"}

[dev-dependencies]
cosmwasm-schema = {version = "0.13.0"}


