url: http://testnet-lcd.orai.io
chain_id: Oraichain-testnet
denom: orai
contract: orai1fjmwk4t98vpt2y54j0why5l98euqfgqelcf3wx
ping_contract: orai1nxjz9ys32w7xfwc7ecdm6ndzwuhp7c0d90n5pc
interval: 10000
