url: http://testnet-lcd.orai.io
chain_id: Oraichain-testnet
denom: orai
contract: orai1zu23f0ql5xtyr5p7zdge7l2gtflrxeajtu93fu
ping_contract: orai1nxjz9ys32w7xfwc7ecdm6ndzwuhp7c0d90n5pc
interval: 6000
ping_interval: 30000
